site_name: gandlf
site_description: "Gandlf: Generative Adversarial Networks in Keras"
site_author: Benjamin Bolte
repo_url: https://github.com/codekansas/gandlf
theme: readthedocs

pages:
- Home: index.md
- Background: background.md
- Examples:
  - XOR: examples/xor.md
#   - MNIST: examples/mnist.md

