site_name: gandlf
site_description: "Gandlf: Generative Adversarial Networks in Keras"
site_author: Benjamin Bolte
repo_url: https://github.com/codekansas/gandlf
theme: readthedocs

pages:
- Home: index.md
- Background: background.md
- Model: model.md
- Tricks: tricks.md
- Layers:
  - Core: layers/core.md
  - Attention: layers/attention.md
  - Wrappers: layers/wrappers.md
- Callbacks: callbacks.md
- Losses: losses.md
- Examples:
  - Hello, world!: examples/xor.md
  - MNIST GAN: examples/mnist/mnist_gan.md
  - Upsampling GAN: examples/upsample.md
  - Reversing Generator: examples/reverse.md

